export const ABILITY_LOAD_DATA = 'ABILITY_LOAD_DATA';
export const ABILITY_DATA_LOADED = 'ABILITY_DATA_LOADED';
export const ABILITY_SET_FETCHING = 'ABILITY_SET_FETCHING';
export const ABILITY_SET_ERROR = 'ABILITY_SET_ERROR';
export const ABILITY_EXECUTE = 'ABILITY_EXECUTE';
