export const POKEMON_LOAD_DATA = 'POKEMON_LOAD_DATA';
export const POKEMON_DATA_LOADED = 'POKEMON_DATA_LOADED';
export const POKEMON_SET_FETCHING = 'POKEMON_SET_FETCHING';
export const POKEMON_SET_ERROR = 'POKEMON_SET_ERROR';
export const POKEMN_EXECUTE = 'POKEMN_EXECUTE';
