export const POKEMONS_LOAD_DATA = 'POKEMONS_LOAD_DATA';
export const POKEMONS_DATA_LOADED = 'POKEMONS_DATA_LOADED';
export const POKEMONS_SET_FETCHING = 'POKEMONS_SET_FETCHING';
export const POKEMONS_SET_QUERY_STRING = 'POKEMONS_SET_QUERY_STRING';
export const POKEMONS_SET_ERROR = 'POKEMONS_SET_ERROR';
